### ISSUE TITLE
Before/After hooks not executing in feature-scoped registry mode (1.2.3)

### ISSUE THREAD

**Issue by deepracticexs** [Deepractice/VitestCucumber#24]
## Description

After the feature-scoped registry implementation (PR #19, version 1.2.3), Before/After hooks defined in step definition files are not being executed during test runs.

## Environment

- `@deepracticex/vitest-cucumber`: 1.2.3
- `@deepracticex/vitest-cucumber-plugin`: 1.2.3
- `vitest`: 3.2.4
- Node.js: 22.14.0

## Steps to Reproduce

1. Create a feature file with scenarios:
```gherkin
Feature: Test
  Background:
    Given setup step
  
  Scenario: Test 1
    Given test step
```

2. Define Before hook in step definition file:
```typescript
import { Before, Given } from '@deepracticex/vitest-cucumber';

Before(async function() {
  console.log('Before hook executing');
  // Initialize test state
});

Given('setup step', function() { });
Given('test step', function() { });
```

3. Run the test with `vitest run`

## Expected Behavior

- Before hook should execute before each scenario
- Console log "Before hook executing" should appear
- Test state should be initialized

## Actual Behavior

- Before hook does NOT execute
- No console output from Before hook
- Test state is not initialized
- Tests that depend on Before hook initialization fail

## Root Cause Analysis

The issue is related to how feature-scoped registries interact with hook registration:

1. **During step file import** (when generated test code loads):
   ```javascript
   // Generated code sets feature context
   __setCurrentFeatureContext__({
     stepRegistry: __featureStepRegistry__,
     hookRegistry: __featureHookRegistry__,
   });
   
   // Import step files - Before hooks register HERE
   import '/tests/e2e/steps/test.steps';
   
   // Context is cleared immediately after import
   __setCurrentFeatureContext__(null);
   ```

2. **Hook registration** (`Before()` function calls `HookRegistry.getInstance()`):
   - With feature context active: registers to `__featureHookRegistry__`
   - Hooks ARE being registered to the correct registry

3. **Hook execution** (in generated beforeEach/it blocks):
   ```javascript
   await __featureHookRegistry__.executeHooks('Before', cucumberContext);
   ```
   - This SHOULD work but hooks are not executing

## Investigation Results

Testing shows:
- ✅ Hooks ARE being registered (verified with `registry.getHooks('Before').length === 3`)
- ✅ Hooks are in the correct registry (`__featureHookRegistry__`)
- ❌ But `executeHooks('Before', context)` is not calling the hook functions

This suggests the bug is in either:
- The `HookRegistry.executeHooks()` method
- The context passing mechanism
- The hook function binding

## Workaround

Currently, there is no workaround other than:
1. Downgrade to 1.2.2 (but that has the `__setCurrentFeatureContext__ is not a function` bug #21)
2. Initialize state manually in each Given step instead of using Before hooks

## Impact

This is a **critical regression** that breaks a core Cucumber BDD feature. Any project relying on Before/After hooks for test setup/teardown will fail after upgrading to 1.2.3.

## Additional Context

- This worked correctly before PR #19 (feature-scoped registries)
- The feature-scoped registry design itself seems sound
- The bug appears to be in the execution mechanism, not the registration

---

Related: #21 (runtime exports bug - fixed in 1.2.3)
Introduced by: #19 (feature-scoped registries)
